Panels:
  - Class: rviz/Displays
    Help Height: 78
    Name: Displays
    Property Tree Widget:
      Expanded:
        - /Global Options1
        - /TF1
        - /Spinning LiDAR1
        - /Dome LiDAR1
      Splitter Ratio: 0.55
    Tree Height: 720
  - Class: rviz/Views
    Expanded:
      - /Current View1
    Name: Views
Visualization Manager:
  Class: ""
  Displays:
    - Alpha: 0.45
      Cell Size: 1
      Class: rviz/Grid
      Color: 120; 120; 125
      Enabled: true
      Name: Ground Grid
      Normal Cell Count: 0
      Offset:
        X: 0
        Y: 0
        Z: 0
      Plane: XY
      Plane Cell Count: 20
      Reference Frame: base_footprint
      Value: true
    - Alpha: 1
      Class: rviz/Axes
      Enabled: true
      Length: 0.6
      Name: Base Footprint
      Radius: 0.025
      Reference Frame: base_footprint
      Value: true
    - Class: rviz/Marker
      Enabled: true
      Marker Topic: /rur53/cad_model
      Name: RUR53 CAD Model
      Namespaces:
        rur53: true
      Queue Size: 10
      Value: true
    - Class: rviz/TF
      Enabled: true
      Frame Timeout: 15
      Frames:
        All Enabled: true
      Marker Scale: 0.35
      Name: TF
      Show Arrows: true
      Show Axes: true
      Show Names: true
      Tree: {}
      Update Interval: 0
      Value: true
    - Alpha: 1
      Autocompute Intensity Bounds: true
      Autocompute Value Bounds:
        Max Value: 10
        Min Value: -10
        Value: true
      Axis: Z
      Channel Name: intensity
      Class: rviz/PointCloud2
      Color: 70; 255; 120
      Color Transformer: FlatColor
      Decay Time: 0
      Enabled: true
      Invert Rainbow: false
      Max Color: 255; 255; 255
      Min Color: 0; 0; 0
      Name: Spinning LiDAR
      Position Transformer: XYZ
      Queue Size: 10
      Selectable: true
      Size (Pixels): 2
      Size (m): 0.025
      Style: Points
      Topic: /ouster/points
      Unreliable: false
      Use Fixed Frame: true
      Use rainbow: true
      Value: true
    - Alpha: 1
      Autocompute Intensity Bounds: true
      Autocompute Value Bounds:
        Max Value: 10
        Min Value: -10
        Value: true
      Axis: Z
      Channel Name: intensity
      Class: rviz/PointCloud2
      Color: 255; 145; 40
      Color Transformer: FlatColor
      Decay Time: 0
      Enabled: true
      Invert Rainbow: false
      Max Color: 255; 255; 255
      Min Color: 0; 0; 0
      Name: Dome LiDAR
      Position Transformer: XYZ
      Queue Size: 10
      Selectable: true
      Size (Pixels): 2
      Size (m): 0.025
      Style: Points
      Topic: /ousterDome/points
      Unreliable: false
      Use Fixed Frame: true
      Use rainbow: true
      Value: true
    - Class: rviz/Image
      Enabled: true
      Image Topic: /rgb/image_raw
      Max Value: 1
      Median window: 5
      Min Value: 0
      Name: Azure RGB
      Normalize Range: true
      Queue Size: 2
      Transport Hint: raw
      Unreliable: false
      Value: true
  Enabled: true
  Global Options:
    Background Color: 18; 22; 30
    Default Light: true
    Fixed Frame: base_footprint
    Frame Rate: 30
  Name: root
  Tools:
    - Class: rviz/Interact
      Hide Inactive Objects: true
    - Class: rviz/MoveCamera
    - Class: rviz/Select
    - Class: rviz/FocusCamera
    - Class: rviz/Measure
    - Class: rviz/SetInitialPose
      Topic: /initialpose
    - Class: rviz/SetGoal
      Topic: /move_base_simple/goal
    - Class: rviz/PublishPoint
      Single click: true
      Topic: /clicked_point
  Transformation:
    Current:
      Class: rviz/TF
  Value: true
  Views:
    Current:
      Class: rviz/Orbit
      Distance: 4.2
      Enable Stereo Rendering:
        Stereo Eye Separation: 0.06
        Stereo Focal Distance: 1
        Swap Stereo Eyes: false
        Value: false
      Field of View: 0.785398
      Focal Point:
        X: 0
        Y: 0
        Z: 0.35
      Focal Shape Fixed Size: true
      Focal Shape Size: 0.05
      Invert Z Axis: false
      Name: Current View
      Near Clip Distance: 0.01
      Pitch: 0.48
      Target Frame: base_footprint
      Yaw: 0.78
    Saved: ~
Window Geometry:
  Displays:
    collapsed: false
  Height: 920
  Hide Left Dock: false
  Hide Right Dock: false
  QMainWindow State: 000000ff00000000fd00000004
  Views:
    collapsed: false
  Width: 1520
  X: 80
  Y: 45
